### ISSUE TITLE
Issue a new Release with Improvements

### ISSUE THREAD

**Issue by mmcky** [executablebooks/sphinx-proof#17]
Thanks @najuzilu -- when you're ready it would be great to get a new release. There are some great improvements that have been merged.

**Comment by jstac** [comment]
Actually, would love to have one more feature before the new release.  In addition to `exercise`, could we please have `solution`?

The styling can be the same as proof. 

Even more awsome would be `{proof:solution:exercise_label}` or some other syntax --- whatever works --- that produces

"Solution to Exercise X"

as a header and then gives the same styling as proof. :grimacing:

**Comment by najuzilu** [comment]
We'll issue a new release as soon as we merge the new `solution` directive. I'm very close to being done -- just finalizing tests and documentation.

**Comment by najuzilu** [comment]
v0.0.3 is out and it includes a changelog 🎉
