### ISSUE TITLE
EBP package?

### ISSUE THREAD

**Issue by mmcky** [executablebooks/sphinx-proof#3]
If @najuzilu is agreeable -- once we help with `test` and iron out any bugs we come across -- perhaps we can move this over to `ExecutableBooks` organisation and keep @najuzilu as the lead maintainer for the project. 

I think a lot of other users will want this extension. 

If @najuzilu would rather keep it in her own account -- we can add it to an extension list.

The benefit of migrating to EBP is higher visibility and greater community contribution and support.

**Comment by najuzilu** [comment]
Moving it over to EBP makes a lot of sense. I'm down to migrate it as soon as the bugs have been fixed.

**Comment by mmcky** [comment]
thanks @najuzilu once the current PR's are merged I think we can migrate to `executable books` organisation.

**Comment by mmcky** [comment]
hey @najuzilu let me know when you're ready to migrate to `EBP`. Looks like most of the things in the developer guide have been added now. Is that right?

**Comment by choldgraf** [comment]
Hey all - just voicing my support for this idea if the general plan is to move this to EBP. I think that we should try to standardize on that github org so that it's easier to keep track of development across these projects.

**Comment by najuzilu** [comment]
@mmcky I'm happy to migrate the repo to EBP anytime. :-)

@choldgraf would I need to do anything regarding Netlify, RTD and PyPI?

**Comment by choldgraf** [comment]
we'll need to update the RTD to point to the new repository, but I think that should be it. (unless you're also using netlify in this repo as well?)

**Comment by najuzilu** [comment]
@choldgraf I'm using Netlify and Codecov.

**Comment by choldgraf** [comment]
ah gotcha 👍 we can add netlify to this one as well, though is there a reason that you're not using readthedocs? (AKA, would you mind if we switched to RTD?)

**Comment by najuzilu** [comment]
Already ahead of you - we're using RTD (see [here](https://sphinxcontrib-prettyproof.readthedocs.io/en/latest/)).

I was able to setup Netlify deploy-preview for PRs and submitted a request to EBP to get access to Codecov.

**Comment by choldgraf** [comment]
Nice! Why don't we just use the ReadTheDocs PR previewer instead of using both RTD and Netlify? (if you add me to the RTD site then I can add it but I believe the setting is under `settings -> advanced` something like that)

**Comment by najuzilu** [comment]
Sorry - just getting around to this @choldgraf. You should have received an email. :-)

**Comment by choldgraf** [comment]
I approved it 👍
