### ISSUE TITLE
Could not import extension sphinxcontrib.prettyproof?

### ISSUE THREAD

**Issue by nathanael-fijalkow** [executablebooks/sphinx-proof#45]
I was very happy to find out about Prettyproof, however I cannot seem to import it...

I'm new to JupyterBook, so maybe I've done something silly?

I pip installed the extension successfully, and then added it here in my _config.yml
sphinx:
  extra_extensions:
     - sphinxcontrib.prettyproof

I get the following error:

Extension error:
Could not import extension sphinxcontrib.prettyproof (exception: No module named 'sphinxcontrib.prettyproof')
Traceback (most recent call last):
  File "/home/nathanael/.local/lib/python3.6/site-packages/sphinx/registry.py", line 409, in load_extension
    mod = import_module(extname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sphinxcontrib.prettyproof'

Many thanks for your help!
Nath

**Comment by najuzilu** [comment]
Hi @nathanael-fijalkow, thanks for your feedback. I've just tested this on a branch of [jupyter-book](https://github.com/najuzilu/jupyter-book/tree/test-sphinxcontrib-prettyproof) and I did not run into any issues. Can you make sure `pip list` includes `sphinxcontrib-prettyproof`?

Let me walk you through the steps I took to build this locally in case it helps (note that I use Anaconda):

1. `conda create -n prettyproof pip` and `conda activate prettyproof`
2. `pip install sphinxcontrib-prettyproof`
3. install any jupyter-book document-related packages
4. add `sphinxcontrib-prettyproof` under `extra_extensions`:
    ```
    sphinx:
        extra_extensions:
            - sphinxcontrib.prettyproof
    ```
5. `jb clean docs` and `jb build docs`
 
Another option would be to clone this repo and run `pip install -e.`.

**Comment by nathanael-fijalkow** [comment]
Many thanks @najuzilu for the quick and detailed reply! The import seems to work now, except that I get warnings of the form:
WARNING: Unknown directive type "proof:proof". 
WARNING: Unknown directive type "proof:theorem".

Sorry for the naive questions! (I did look around but cannot figure it out...)

**Comment by najuzilu** [comment]
I need more details in order to help. How are you installing `sphinxcontrib-prettyproof`? What is the content of `_config.yml`? Can you give me an example of how you introduce the directives in the book?

If you have the project on Github, I can take a quick look. :-)

**Comment by najuzilu** [comment]
I also setup https://github.com/najuzilu/jupyterbook_proof_example which walks you through all the steps used to successfully build Jupyter Book with sphinxcontrib-prettyproof.

**Comment by najuzilu** [comment]
We've moved away from `sphinxcontrib-prettyproof` so I'll close this issue. Please open a new issue if you have any problems installing the newly named extension @nathanael-fijalkow.
