### ISSUE TITLE
Sphinx v3.3 upgrade breaks enumerable nodes with no title

### ISSUE THREAD

**Issue by najuzilu** [executablebooks/sphinx-proof#48]
**Describe the bug**

https://github.com/sphinx-doc/sphinx/commit/66dda1fc50249e9da62e79380251d8795b8e36df breaks enumerable nodes with no title because they're no longer added to `env.toc_fignumbers`.

**To Reproduce**

Run the current docs with `sphinx = 3.3.0 `. The break is introduced in `my-lemma` and persists for all enumerable nodes with no explicit title.

**Expected behavior**

IMO enumerable nodes with no title should be numbered.

**Environment**

- Python Version: 3.8.5
- Sphinx version: 3.3.0
- Operating System: MacOS

**Comment by AakashGfude** [comment]
Thanks, @najuzilu for raising this one. The issue has been fixed now in `v0.1.0`.
