### ISSUE TITLE
Title required for most directives

### ISSUE THREAD

**Issue by nathanael-fijalkow** [executablebooks/sphinx-proof#50]
Hi,
It seems that contrary to what's in the documentation, titles are required for all directives except proof (using jupyter-book).

If I write:

````
```{prf:theorem}
Content
```
````

I get the following "There was an error in building your book.".
More details:

Exception occurred:
  File "XXXXX/.local/lib/python3.8/site-packages/sphinx_proof/nodes.py", line 36, in depart_enumerable_node
    idx = self.body.index(f"Proof {number} ")
ValueError: 'Proof  ' is not in list

It works well if I add a title: 

````
```{prf:theorem} Theorem title
Content
```
````

Is it possible to make the title optional?

Thanks for your help!
Nath

**Comment by AakashGfude** [comment]
Hi @nathanael-fijalkow , sorry for the late reply. This issue should be fixed in `v0.1.0` onwards.
