### ISSUE TITLE
Advanced numbering options: distinct for different directives, reset for each section

### ISSUE THREAD

**Issue by nathanael-fijalkow** [executablebooks/sphinx-proof#52]
Hi,

It seems that there are two options for now: either everything is numbered, or nothing. Is there a way to:
* number independently Theorems, Examples, Lemmas, etc?
* reset the numbers in each section, or part?

Many thanks!
Nath

**Comment by AakashGfude** [comment]
Hi @nathanael-fijalkow , we have implemented independent numbering for different directives, in this PR https://github.com/executablebooks/sphinx-proof/pull/62, and will be available in `v0.1.1`.

But, numbering between different sections, parts has not been much in demand for this extension.  I can see numbering between different parts of a toctree being useful, but not sure about numbering between different sections. 
If this is something that is absolutely necessary for you, and you see it being used in other projects, please feel free to convince us.

**Comment by mscharling** [comment]
@AakashGfude I have some problems with numbering which I've stated [here](https://github.com/executablebooks/meta/discussions/612). I guess this can be related to this question.

**Comment by jkeneda** [comment]
I just wanted to second the feature request for a way to reset the numbering for a given directive at arbitrary points.  I'm trying to use this extension for a Jupyter Book project to build a textbook replacement for my students, and I love having the theorem/proof/example environments, but it does feel unusual to open a chapter with Example 72.
