### ISSUE TITLE
sphinx-proof trying to access parts of sphinx.ast that don't exist 

### ISSUE THREAD

**Issue by mmcky** [executablebooks/sphinx-proof#60]
### Describe the problem

@AakashGfude I am trying to build: https://github.com/jstac/continuous_time_mcs and betting the following traceback. 

```
Exception occurred:
  File "/Users/matthewmckay/anaconda3/lib/python3.8/site-packages/sphinx_proof/domain.py", line 106, in resolve_xref
    map(str, env.toc_fignumbers[todocname]["proof"][target])
KeyError: 'equivirr'
```

so it looks like `sphinx-proof` is trying to access parts of the `sphinx.ast` that don't exist.

### Link to your repository or website

https://github.com/jstac/continuous_time_mcs

### Steps to reproduce

1. Build project

**Comment by AakashGfude** [comment]
Hey, @mmcky  I tried running this repository with sphinx-proof - v0.1.0. And could not replicate this issue.

**Comment by mmcky** [comment]
ok thanks @AakashGfude I will try this again then.

**Comment by mmcky** [comment]
I confirm this is now the case 👍
