### ISSUE TITLE
Strange scrollbar appearing in the rendering of a labeled equation

### ISSUE THREAD

**Issue by shailesh1729** [executablebooks/sphinx-proof#74]
### Describe the problem

There is a horizontal scroll bar appearing below a labeled equation. 

![image](https://user-images.githubusercontent.com/8783308/148695345-e533a31e-ea9d-49f0-be5c-d6cd9a915c7e.png)

The problem appears to be in the stylesheet

![image](https://user-images.githubusercontent.com/8783308/148695432-358c2528-1c5e-4da7-90a1-886bbc878aa3.png)

In the `main.bd-content #main-content div.math`  `overflow-x: auto` setting.  If I remove this setting, then scroll bar goes away but rendering gets messed up in other places. 

Strangely, the problem appears to be local on my Windows laptop.  You can see it rendered from the github-pages link:

https://www.indigits.com/cvx-opt-book/basic_real_analysis/differentiability.html#equation-eq-bra-df-f-minus-tangent

When I built from the same code on Netlify (using Linux OS), the problem is gone:

https://convex.indigits.com/basic_real_analysis/differentiability.html#equation-eq-bra-df-f-minus-tangent

### Link to your repository or website

https://www.indigits.com/cvx-opt-book/basic_real_analysis/differentiability.html

### Steps to reproduce

Here is the markdown code of the lemma:

```````
````{prf:lemma}
If $f$ is differentiable at $x=a$, then

```{math}
:label: eq-bra-df-f-minus-tangent
f(x) = f(a) + [f'(a) + E(x)](x -a)
```
where $E$ is defined in the neighborhood of $x=a$ and

$$
\lim_{x \to a} E(x) = E(a) = 0.
$$
````
```````

The whole Jupyter Book is hosted on https://github.com/shailesh1729/cvx-opt-book . 
The particular Markdown file is https://github.com/shailesh1729/cvx-opt-book/blob/main/book/basic_real_analysis/differentiability.md. 

### The version of Python you're using

3.8.12

### Your operating system

Windows 10

### Versions of your packages

```
Jupyter Book      : 0.12.1
External ToC      : 0.2.3
MyST-Parser       : 0.15.2
MyST-NB           : 0.13.1
Sphinx Book Theme : 0.1.7
Jupyter-Cache     : 0.4.3
NbClient          : 0.5.9
```

**Comment by TimRoith** [comment]
Are you sure this is an issue of sphinx-proof?

I noticed the same behaviour here

https://github.com/executablebooks/sphinx-book-theme/issues/432

without a proof directive.
In my case it turned out that it was an issue with the sphinx-book-theme that was fixed here

https://github.com/executablebooks/sphinx-book-theme/pull/447.

**Comment by shailesh1729** [comment]
Indeed it was an issue of ` sphinx-book-theme`. After I upgraded to the latest 0.2.0 version of the theme, the issue is gone. Thank you for pointing it out.
