### ISSUE TITLE
Unable to use sphinx-proof in markdown cells of Jupyter Notebooks

### ISSUE THREAD

**Issue by schwabts** [executablebooks/sphinx-proof#89]
### Describe the bug

**context**
When I write the following into markdown cells of Jupyter Notebooks:
`````
````{prf:remark} context
Important remark
````
`````

**expectation**
I expected the remarks to get rendered in beautiful coloured boxes.

**bug**
But instead the remarks are shown as ordinary typewriter text.

**problem**
My use case is to add computational contents to a page in a Jupyter Book project which already contains many sphinx-proof directives. I would naturally prefer to make just one part of this markdown file executable but copying the available contents into markdown cells of a Jupyter Notebook was a quicker approach for now. Is there a better solution for this?

Otherwise, this looks more like the need for an nbextension to me than a problem with sphinx-proof itself but making sphinx-proof available to markdown cells in Jupyter Notebooks might require some sort of update to sphinx-proof as well from my distant point of view.

### Reproduce the bug

Reproduce as explained above

### List your environment

Jupyter Book      : 0.13.0
External ToC      : 0.2.4
MyST-Parser       : 0.15.2
MyST-NB           : 0.13.2
Sphinx Book Theme : 0.3.3
Jupyter-Cache     : 0.4.3
NbClient          : 0.5.3

**Comment by schwabts** [comment]
* `jb build book/` helped to get the sphinx-proof directives rendered as intended in the static HTML output.
* rendering them this way in a Jupyter Notebook likely is to be considered somewhere else.

**Comment by mmcky** [comment]
@schwabts thanks for the bug report. 

That's right -- these `myst` directives only work via `jupyter-book` and are not rendered within jupyter notebook natively. That is something that is getting worked on (as the `mystjs` project develops in parallel) and hopefully we can rendered these within the notebook at that time.

**Comment by mmcky** [comment]
https://github.com/executablebooks/jupyterlab-myst
